# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Kaggle Graph Actions
    uses: OliverSieweke/kaggle-graph@v0.1.0
    with:
    # Competition ID
    KAGGLE_COMPETITION_ID: titanic 
